[build-system]
requires = ["uv_build>=0.12.7,<0.13"]
build-backend = "uv_build"

[project]
name = "appimage"
version = "2.0.1"
authors = [
    {name = "SSH-MITM Dev-Team", email = "support@ssh-mitm.at"}
]
maintainers = [
  {name = "Manfred Kaiser", email = "manfred.kaiser@ssh-mitm.at"}
]
description = "Package Python applications as self-contained AppImages"
readme = "README.md"
license = {text = "Apache-2.0"}
keywords = [
    "appimage",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Build Tools",
    "Topic :: System :: Software Distribution",
    "Development Status :: 5 - Production/Stable",
]
requires-python = ">= 3.11"

[project.optional-dependencies]
docs = [
    "myst-parser",
    "sphinx",
    "sphinx-copybutton",
    "sphinx-rtd-theme",
]

[project.scripts]
appimagectl = "appimage.ctl.__main__:main"

[project.urls]
Homepage = "https://github.com/ssh-mitm/appimage"
Documentation = "https://appimage.readthedocs.io"
Changelog = "https://github.com/ssh-mitm/appimage/blob/main/CHANGELOG.md"
Source = "https://github.com/ssh-mitm/appimage"
Tracker = "https://github.com/ssh-mitm/appimage/issues"

[tool.uv.build-backend]
module-root = ""

[tool.hatch.envs.hatch-test]
dependencies = ["pytest"]

[tool.hatch.envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args:tests/}"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.11", "3.12", "3.13", "3.14"]

[tool.hatch.envs.docs]
detached = false
features = ["docs"]

[tool.hatch.envs.docs.scripts]
build = ["sphinx-build docs build/html"]

[tool.hatch.envs.test]
dependencies = ["pytest"]

[tool.hatch.envs.test.scripts]
run = "pytest tests/"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.envs.lint]
detached = false
dependencies = [
    "bandit",
    "black~=26.0",
    "Flake8-pyproject",
    "flake8",
    "mypy",
    "pylint",
    "pytest",
    "ruff",
]

[tool.hatch.envs.lint.scripts]
check = [
    "pytest",
    "black --check appimage",
    "bandit -r appimage",
    "ruff check appimage",
    "flake8 appimage",
    "pylint appimage",
    "mypy appimage",
]

[[tool.hatch.envs.lint.matrix]]
python = ["3.11", "3.12", "3.13", "3.14"]

[tool.flake8]
ignore = ["E203", "E501", "W503"]

[tool.mypy]
strict = true
install_types = true
non_interactive = true

[tool.pylint]
disable = [
    "line-too-long",
    "too-many-instance-attributes",
]

[tool.pylint.design]
max-args = 7
max-locals = 26
max-module-lines = 2600

[tool.pylint.MASTER]
load-plugins = "pylint.extensions.docparams"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",    # one-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "E501",    # Line too long
]

[tool.ruff.lint.pylint]
max-args = 7

[tool.ruff.lint.flake8-copyright]
author = "SSH-MITM Dev-Team"

[tool.black]
target-version = ["py311"]

[tool.bumpversion]
current_version = "2.0.1"

[[tool.bumpversion.files]]
filename = "appimage/__init__.py"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "[Unreleased]: https://github.com/ssh-mitm/appimage/compare/{current_version}...main"
replace = """[Unreleased]: https://github.com/ssh-mitm/appimage/compare/{new_version}...main
[{new_version}]: https://github.com/ssh-mitm/appimage/compare/{current_version}...{new_version}"""

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "## [Unreleased]"
replace = """## [Unreleased]

## [{new_version}] - {now:%Y-%m-%d}"""